language: node_js
node_js:
  - 12
deploy:
  app: torm
  on: dev
before_script:
  - apk add --update npm lcms2-dev libpng-dev gcc g++ make autoconf automake
script:
  - apk add --no-cache rsync openssh
  - mkdir -p ~/.ssh
  - echo "$DEV_ENV" > .env
  - ssh-keyscan -H '13.212.177.234'  >> ~/.ssh/known_hosts
  - echo "$DEV_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo '*** Starting build ***'
  - echo 'install dependencies'
  - npm install --silent
  - npm run --silent build
  - rsync --progress -avzh --exclude 'node_modules' -e "ssh -i ~/.ssh/id_rsa " --rsync-path="sudo rsync" . ubuntu@13.212.177.234:/var/www/html/new_torm-api
  - ssh -i ~/.ssh/id_rsa ubuntu@13.212.177.234 "cd /var/www/html && sudo mv torm-api tmp_torm-api && sudo mv new_torm-api torm-api && sudo rm -rf tmp_torm-api && sudo chmod -R 777 /var/www/html/torm-api && cd /var/www/html/torm-api"
