language: node_js
node_js:
  - 12
script:
  - echo '*** Starting build ***'
  - echo 'install dependencies'
  - npm install
  - echo 'Running test'
  - npm run build
deploy:
  provider: gae
  project: teak-truck-264015
  keyfile: gae.json
  app: torm
  on: master
