#before_install:
#- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out deploy_rsa -d

language: node_js
node_js:
  - 12
addons:
  ssh_known_hosts: 13.212.177.234
before_deploy:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  cleanup: true
  #script: ssh ubuntu@13.212.177.234 'bash ./deploy.sh'
  on:
    branch: dev
script:
  - ssh ubuntu@13.212.177.234
  - echo "Changing directory to ~/torm"
  - cd torm
  - echo "Pulling from git"
  - git pull origin dev
  - echo "Install"
  - npm install
  - echo "Build"
  - npm run build
  - echo "Restarting pm2 instances"
  - pm2 restart all
