name: Deploy Testing

on: [ push, pull_request ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../id_rsa_test
          sudo chmod 600 ../id_rsa_test
          # echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          ssh-keyscan -H ${{secrets.KNOWN_HOSTS}} > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.KNOWN_HOSTS}}
      - name: Create Enviroment
        run: |
          echo "$ENVIROMENT" > .env
        env:
          ENVIROMENT: ${{secrets.ENV}}
      - name: SSH into DO and run
        run: >
          rsync --progress -avzh --exclude='.git' -e "ssh -i ~/.ssh/id_rsa_test " --rsync-path="rsync" . ubuntu@"$HOST":/home/ubuntu/new_torm
          && ssh -i ../id_rsa_test -tt ubuntu@"$HOST"
          "mv torm tmp_torm && mv new_torm torm && rm -rf tmp_torm && cd torm && npm install -f && npm run build && pm2 restart service.json"
        env:
          HOST: ${{secrets.KNOWN_HOSTS}}